name: Docker image CI

on:
  push:
    tags:
      - "*"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: thecloudco
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from tag
        id: version
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/}"

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: thecloudco/inferex:${{ steps.version.outputs.version }}
